import { getGeneratedCardsByUser } from "@/lib/cards";
import Link from "next/link";
import Container from "../components/Container";

export default async function GeneratedCardsList({ userId, name, isCurrentUserDashboard }: { userId: string, name: string, isCurrentUserDashboard: boolean }) { // Accept userId prop
    if (!userId) { // Check if userId is provided
        return null;
    }

    const generatedCards = await getGeneratedCardsByUser(userId); // Use userId prop

    return (
        <Container className="flex flex-col gap-6 mt-6" shadow >
            {isCurrentUserDashboard ? <h4>My Generated Cards</h4> : <h4>Cards Generated by {name}</h4>}
            {generatedCards.length > 0 ? (
                <ul className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                    {generatedCards.map(card => (
                        <li key={card.id}>
                            <Link href={`/learn/${card.id}`}>
                                <div className="bg-gray-100 text-base text-center h-full shadow rounded-lg flex flex-col items-center justify-center p-2 transition-all hover:bg-(--primary)/20 hover:scale-105 hover:text-bold!">
                                    {card.korean}<br />
                                    {card.character}
                                </div>
                            </Link>
                        </li>
                    ))}
                </ul>
            ) : (
                <p className="text-gray-500">No cards generated by this user yet.</p> // Updated message
            )}
        </Container>
    );
}
